-- V3__create_proposal.sql
-- PROPOSAL 테이블 DDL

CREATE TABLE proposal (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      BIGINT       NOT NULL REFERENCES curation_request(id),
    flower_shop_id  BIGINT       NOT NULL REFERENCES flower_shop(id),
    status          VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    concept_title   VARCHAR(255),
    mood_color_json TEXT,
    main_flowers_json TEXT,
    wrapping_style_json TEXT,
    allergy_note    VARCHAR(255),
    care_tips       TEXT,
    description     TEXT         NOT NULL,
    image_urls_json TEXT,
    available_slot_kind  VARCHAR(30) NOT NULL,
    available_slot_value VARCHAR(30) NOT NULL,
    price           DECIMAL(10,0) NOT NULL CHECK (price > 0),
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    expires_at      TIMESTAMP    NOT NULL,
    submitted_at    TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_proposal_request_id ON proposal (request_id);
CREATE INDEX idx_proposal_request_id_status ON proposal (request_id, status);
CREATE INDEX idx_proposal_flower_shop_id ON proposal (flower_shop_id);
