spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret-key: ${JWT_SECRET_KEY}

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS_PATH}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
      region: ${AWS_REGION:ap-northeast-2}
      presigned-url-expiration: 600

kakao:
  local:
    base-url: https://dapi.kakao.com
  rest-key: ${KAKAO_REST_KEY}
